<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Base\Model\Logger;

use Magento\Framework\Logger\Monolog;
use FjodorMaller\Base\Api\FjodorMallerHelperInterface;

/**
 * Class BaseLogger
 */
abstract class BaseLogger extends Monolog
{
    /**
     * @var FjodorMallerHelperInterface
     */
    protected $_helper;

    /**
     * @param FjodorMallerHelperInterface $helper
     *
     * @inheritdoc
     */
    public function __construct(
        $name,
        FjodorMallerHelperInterface $helper,
        array $handlers = [],
        array $processors = []
    ) {
        $this->_helper = $helper;
        parent::__construct($name, $handlers, $processors);
    }

    /**
     * @inheritdoc
     */
    public function addRecord($level, $message, array $context = [])
    {
        if ($this->_helper && !$this->_helper->isLoggingEnabled()) {
            return true;
        }

        return parent::addRecord($level, $message, $context);
    }
}
