<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Base\Ui\Component\Form\Status;

use FjodorMaller\Base\Model\System\Config\Source\Status;
use Magento\Framework\Data\OptionSourceInterface;

/**
 * Class Options
 */
class Options implements OptionSourceInterface
{
    /**
     * @var array
     */
    protected $_options;

    /**
     * @inheritdoc
     */
    public function toOptionArray()
    {
        if (!$this->_options) {
            $this->_options = [];
            foreach (Status::toArray() as $value => $label) {
                $this->_options[] = [
                    'value' => $value,
                    'label' => $label,
                ];
            }
        }

        return $this->_options;
    }
}
