<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Base\Model\System\Config\Source;

use FjodorMaller\Base\Helper\Data;
use Magento\Framework\Option\ArrayInterface;

/**
 * Class Status
 */
class Status implements ArrayInterface
{
    const DISABLED = 0;

    const ENABLED  = 1;

    /**
     * Returns the status map.
     *
     * @return array
     */
    public static function toArray()
    {
        return [
            static::DISABLED => __('Disabled'),
            static::ENABLED  => __('Enabled'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function toOptionArray()
    {
        return Data::toOptions(self::toArray());
    }
}
