<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Base\Model\System\Config\Source;

use FjodorMaller\Base\Helper\Data;
use Magento\Framework\Option\ArrayInterface;

/**
 * Class Yesno
 */
class Yesno implements ArrayInterface
{
    const NO  = 0;

    const YES = 1;

    /**
     * Returns the yes/no map.
     *
     * @return array
     */
    public static function toArray()
    {
        return [
            static::NO  => __('No'),
            static::YES => __('Yes'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function toOptionArray()
    {
        return Data::toOptions(self::toArray());
    }
}
