<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Base\Model\Logger\Handler;

use FjodorMaller\Base\Api\FjodorMallerHelperInterface;
use Magento\Framework\Filesystem\DriverInterface;
use Magento\Framework\Logger\Handler\Base as OriginalBaseHandler;

/**
 * Class BaseHandler
 */
abstract class BaseHandler extends OriginalBaseHandler
{
    /**
     * @var FjodorMallerHelperInterface
     */
    protected $_helper;

    /**
     * @param FjodorMallerHelperInterface $helper
     *
     * @inheritdoc
     */
    public function __construct(
        FjodorMallerHelperInterface $helper,
        DriverInterface $filesystem,
        string $filePath = null,
        string $fileName = null
    ) {
        if (!$filePath && strlen($_filePath = $helper->getLoggingLocation())) {
            $filePath = $_filePath;
        }
        if (!$fileName && strlen($_fileName = $helper->getLoggingFilename())) {
            $fileName = $_fileName;
        }
        parent::__construct($filesystem, $filePath, $fileName);
        $this->_helper = $helper;
    }
}
