<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Base\Model\Form;

use FjodorMaller\Base\Api\OptionItemInterface;
use Magento\Framework\DataObject;

/**
 * Class BaseOptionItem
 */
abstract class BaseOptionItem extends DataObject implements OptionItemInterface
{
}
