<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the license that is available in LICENSE file.
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to upgrade this extension to newer version in the future.
 */

namespace FjodorMaller\Base\Api;

interface OptionItemInterface
{
    /**
     * Returns the name.
     *
     * @return string
     */
    public function getName();

    /**
     * Returns the code.
     *
     * @return string
     */
    public function getCode();

    /**
     * Returns the form fields.
     *
     * @return array
     */
    public function getFormFields();
}
